apiVersion: v1
kind: ConfigMap
metadata:
  name: finflow-config
  namespace: finflow
data:
  DB_URL: "jdbc:oracle:thin:@oracle-service:1521/FINFLOW"
  DB_USERNAME: "finflow"
  DB_DRIVER: "oracle.jdbc.OracleDriver"
  DB_DIALECT: "org.hibernate.dialect.OracleDialect"
  REDIS_HOST: "redis-service"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  EUREKA_URL: "http://eureka-service:8761/eureka/"
  ML_SERVICE_URL: "http://fraud-ml-service:8000"
  SMTP_HOST: "mailhog-service"
  SMTP_PORT: "1025"
