apiVersion: v1
kind: Secret
metadata:
  name: finflow-secrets
  namespace: finflow
type: Opaque
stringData:
  DB_PASSWORD: "finflow123"
  REDIS_PASSWORD: ""
  JWT_SECRET: "finflow-super-secret-key-2024-very-long-and-secure"
